name: Update Hash

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  
jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Random Hash
        id: generate-hash
        run: echo "hash=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 100)" > hash

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add main/hash
          git commit -m "Auto update hash"
          git push
